services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env

  restaurant-service:
    build:
      context: ./restaurant-service
    ports:
      - "5002:5002"
    env_file:
      - ./restaurant-service/.env

  order-service:
    build:
      context: ./order-service

  delivery-service:
    build:
      context: ./delivery-service
    ports:
      - "5004:5004"
    env_file:
      - ./delivery-service/.env

  customer-service:
    build:
      context: ./customer-service
    ports:
      - "5005:5005"
    env_file:
      - ./customer-service/.env
